spring.application.name=auth-service
server.port=8081
spring.datasource.url=jdbc:h2:mem:authdb
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.h2.console.enabled=true
