spring:
  application:
    name: notification-service
  main:
    allow-bean-definition-overriding: true
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
  datasource:
    url: jdbc:postgresql://localhost:5432/notification_db
    username: postgres
    password: Dagim@2026
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME:dndagi2424@gmail.com}
    password: ${SPRING_MAIL_PASSWORD:qbejmgnetxeagivo}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

logging:
  level:
    root: INFO
    com.ecom.notification: DEBUG

