<project xmlns="http://maven.apache.org/POM/4.0.0">

	<modelVersion>4.0.0</modelVersion>

	<groupId>com.microservices</groupId>
	<artifactId>event-driven-system</artifactId>
	<version>1.0</version>

	<packaging>pom</packaging>

	<modules>
		<module>auth-service</module>
		<module>order-service</module>
		<module>payment-service</module>
		<module>inventory-service</module>
		<module>shipping-service</module>
		<module>notification-service</module>
	</modules>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-dependencies</artifactId>
				<version>3.2.5</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

</project>