server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://34.241.16.247:5432/postgres?currentSchema=auth_service&sslmode=disable
    username: postgres.ixxknffjvcfnkkrhwezt
    password: 8GAgdcQSuWto8w4Y
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: auth_service
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
