server:
  port: 8085

spring:
  datasource:
    url: jdbc:h2:mem:shippingdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest