spring.application.name=shipping-service

server.port=8084

# ====================== Database (PostgreSQL) ======================
spring.datasource.url=jdbc:postgresql://localhost:5432/shipping
spring.datasource.username=postgres
spring.datasource.password=Edu27015
spring.datasource.driver-class-name=org.postgresql.Driver

# ====================== JPA ======================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ====================== RabbitMQ ======================
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Optional Logging
logging.level.org.springframework.amqp=INFO