spring:
  profiles:
    active: dev
    autoconfigure:
      exclude: org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration

server:
  port: 8081
app:
  task:
    default-page-size: 10



