spring.application.name=payment-service

server.port=8082

# ====================== RabbitMQ ======================
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# ====================== PostgreSQL Database ======================
spring.datasource.url=jdbc:postgresql://localhost:5432/payment
spring.datasource.username=postgres
spring.datasource.password=Edu27015
spring.datasource.driver-class-name=org.postgresql.Driver
# Disable type header information
spring.rabbitmq.template.message-converter=org.springframework.amqp.support.converter.Jackson2JsonMessageConverter

# Or use this to trust all packages
spring.amqp.deserialization.trust.all=true
# ====================== JPA Settings ======================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Optional: Nice logging
logging.level.org.springframework.amqp=DEBUG
logging.level.org.hibernate.SQL=DEBUG