spring.application.name=order-service
server.port=8082

# H2 Database
spring.datasource.url=jdbc:h2:mem:ordersdb
spring.h2.console.enabled=true

# RabbitMQ (Assumes Docker is running)
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest