server:
  port: 8081

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/orderdb
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

services:
  inventory:
    base-url: http://localhost:8083
  payment:
    base-url: http://localhost:8082
  shipping:
    base-url: http://localhost:8084
  notification:
    base-url: http://localhost:8085

management:
  endpoints:
    web:
      exposure:
        include: health,info
